### ISSUE TITLE
support hashicopr configuration language

### ISSUE THREAD

**Issue by patdhlk** [paked/configure#2]
hey, 

i love your configure package and we are using it in several applications but some of the guys here want to use hcl instead of json. So why not supporting hcl in this package.

**Comment by paked** [comment]
Hey @patdhlk, it is really awesome to hear that you are using it in a few of your Go packages! I've left a comment or so on your PR, and hope we can get it merged in soon!

**Comment by paked** [comment]
Closed by #3
