### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JC1738** [paked/configure#4]
Thanks for the library.  Enjoyed using it.  One thing would might be nice is to note Environment variables must be ALL capital letters in order for the config lib to pick them up.  It took me a bit to debug why I couldn't get those configuration values to show up until I realized that they needed to be capital.  So some note in documentation would be great.   It's especially hard when you mix other config types.  Another option is to ignore case and allow the environment variables to be lower case.   

I appreciate the lib, thanks again.

**Comment by paked** [comment]
@JC1738 Sorry its taken me so long to get back to you on this. Thank you very much for the suggestion, it really means a lot to me that you like `configure`. I've put this on my TODO list for this weekend.

**Comment by paked** [comment]
Thanks again for reporting this, having people use this library is very validating. If you have any other suggestions or requests, I'd be happy to consider implementing them!
